[build]
  functions = "functions"
[[redirects]]
  force = true
  from = "/scripts/public.js"
  status = 200
  to = "https://joyful-custard-ec7795.netlify.app/scripts/public.js"

  [[redirects]]
  from = "/data.json"
  to = "/.netlify/functions/getStreams"
  status = 200
  force = true